### ISSUE TITLE
404 not found at https://docs.ropensci.org/MtreeRing/articles/app-MtreeRing.html

### ISSUE THREAD

**Issue by lgsmith295** [ropensci/MtreeRing#8]
Missing article on workflow of R shiny GUI. Can this be found somewhere else?

**Comment by JingningShi** [comment]
Thank you for your feedback! I will fix the webpage as soon as possible.
An alternative solution is to download this package from GitHub and extract the file's contents. The workflow of Shiny app is stored in the `\docs\articles` folder.

**Comment by lgsmith295** [comment]
Thank you, Jingning! I'm helping plan a course on tree ring analysis for this spring, which will be delivered online due to coronavirus. I have been looking for a tool for tree ring measurement with a GUI interface (students will not necessarily have experience with R or coding), that is inexpensive or free and can run on multiple operating systems. This seems like a great option. As an R user, I am really excited to see more dendro tools being developed. I could see using this in my own research with the inclusion of an additional feature (ability to mark a crack in the wood, or shift the starting point of the path). I will open a new issue for that, although I do understand if you are not actively developing this at the moment. Thanks again!
